add common components, drag And drop logic and sum order
htmlacademy-vue/192211-pizza-1 pull request #2
Opened 2021-12-17 12:15 UTC by profAlexGit

2021-12-17 13:41 UTC, Djaler requested changes

2021-12-17 13:41 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              <AppDrag :transfer-data="ingredient">
перетаскивание должно отключаться, когда достигнуто максимальное количество для ингредиента

2021-12-17 13:41 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +    <button
эту кнопку тоже нужно отключать, чтоб нельзя было добавить более 3 порций ингредиента

2021-12-17 13:41 UTC, Djaler commented on src/frontend/src/common/components/RadioButton.vue
> +  <label :class="customStyleClass">
если нужно добавить классы на корневой элемент, то необязательно передавать это в пропсах. Можно снаружи на сам компонент назначить class

2021-12-17 13:41 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      ingredient.count = value;
здесь ты меняешь значение в пропсе data напрямую. Нужно создать копию объекта и менять её

2021-12-17 13:41 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +          :class="['pizza__filling', `pizza__filling--${ingredient.type}`]"
нужно учесть вот этот момент ТЗ
![image](https://user-images.githubusercontent.com/7964583/146553014-d09a51c5-41de-4cb9-9c89-7fd8a48623be.png)

2021-12-17 18:11 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      ingredient.count = value;
не исправил вот это

2021-12-17 18:13 UTC, profAlexGit commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      ingredient.count = value;
Я в data сделал копию входных данных из props, и правлю в них.

2021-12-17 18:16 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      ingredient.count = value;
ты копируешь массив, но объекты остаются те же. это не глубокое копирование
можешь попробовать убрать отсюда выброс события, данные всё равно будут меняться.
тебе нужно тут просто сделать что-то вроде
`this.$emit(action, {...ingredient, count: value})`

2021-12-26 10:10 UTC, Djaler commented on build/Makefile
> +# We borrow heavily from the kernel build setup, though we are simpler since
удалить из репозитория, но оставить их локально файлы ты можешь с помощью команды
`git rm --cached file_name` (или `git rm --cached -r directory_name`)

2021-12-26 10:59 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +        this.order.ingredients[indexIngredientInOrder] = ingredient;
Такое изменение вью не отследит
https://ru.vuejs.org/v2/guide/reactivity.html#%D0%94%D0%BB%D1%8F-%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D0%BE%D0%B2

2021-12-26 11:00 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +        ...ingredients.slice(0, indexIngredientInOrder),
а откуда тут `ingredients` ?

2021-12-26 11:02 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +        this.ingredients[oldIngredientIndex] = updatedIngredient;
Аналогично и тут, изменение элемента массива по индексу не реактивно

2021-12-26 11:02 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      this.addIngredient(foundIngredient);
метода addIngredient в этом компоненте нет

2021-12-26 11:02 UTC, profAlexGit commented on src/frontend/src/views/Index.vue
> +        ...ingredients.slice(0, indexIngredientInOrder),
Вот тут да. Не заметил. Спасибо

2021-12-31 15:29 UTC, merged